# load in NumPy (remember to pip install numpy first)

In [6]:
import numpy as np

# The Basics

In [10]:
a = np.array([1,2,3])

In [12]:
print (a)

[1 2 3]


In [18]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [21]:
# Get Diamension of array
a.ndim

1

In [23]:
b.ndim

2

In [25]:
# Get Shape
a.shape

(3,)

In [27]:
b.shape

(2, 3)

In [ ]:
#Get Type

In [29]:
a.dtype

dtype('int64')

In [31]:
b.dtype

dtype('float64')

In [35]:
x= np.array([1,2,3], dtype = 'int16')

In [37]:
x.dtype

dtype('int16')

In [39]:
# Get Size
a.itemsize

8

In [41]:
x.itemsize

2

In [45]:
a.size

3

In [43]:
# Total Size
a.size * a.itemsize

24

In [47]:
a.nbytes

24

In [49]:
b.itemsize

8

In [51]:
b.size

6

In [53]:
b.nbytes

48

In [55]:
b.dtype

dtype('float64')

In [57]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [59]:
a.shape

(2, 7)

In [65]:
# To get an specific element [r, c]/[remember python starts from 0]
a[1,5]

13

In [67]:
a[-1,-2]

13

In [71]:
# Get an spacific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
# get an specific Column
a[ :, 2]

array([ 3, 10])

In [81]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [83]:
a[1, 2:13:1]

array([10, 11, 12, 13, 14])

In [85]:
# if you want to change any element in row/col
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [87]:
a[:,2] = 5
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [91]:
a[:,2] = [1,2]
print (a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# 3-D expample

In [95]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [99]:
# Get specific element (work outside in)
b[0,1,1]

4

In [101]:
b[1,1,1]

8

In [103]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [105]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [111]:
# replace elements here
b[:,1,:] = [[9,9],[8,8]]
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [ ]:
# All 0s matrix

In [122]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [128]:
# All 1s matris
np.ones((2,3,3), dtype= 'int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [138]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [136]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [140]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [142]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [153]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.18631498, 0.27725075],
       [0.76971282, 0.7503129 ],
       [0.95798249, 0.05877943],
       [0.0881996 , 0.71338665]])

In [166]:
# Random Integer Value
np.random.randint(1,5, size=(3,3))

array([[2, 2, 1],
       [4, 2, 1],
       [4, 2, 4]])

In [174]:
# The Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [178]:
#r= Repeat array multiple times
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis = 0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [180]:
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis = 1)
print (r1)

[[1 1 1 2 2 2 3 3 3]]


In [182]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [195]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print (output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [197]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print (output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [204]:
a = np.array([1,2,3])

b = a

print(a)

[1 2 3]


In [206]:
print(b)

[1 2 3]


In [210]:
b[0] = 100
print (b)

[100   2   3]


In [212]:
print (a)

[100   2   3]


In [216]:
a = np.array([1,2,3])

b = a.copy()

print(a)

[1 2 3]


In [218]:
b[0] = 100
print(b)

[100   2   3]


In [220]:
print(a)

[1 2 3]


In [ ]:
# Mathematics

In [222]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [224]:
a + 2

array([3, 4, 5])

In [226]:
a - 2

array([-1,  0,  1])

In [228]:
a * 3

array([3, 6, 9])

In [230]:
a / 2

array([0.5, 1. , 1.5])

In [240]:
b = np.array([1,0,1])

In [242]:
a+b

array([2, 2, 4])

In [244]:
a ** 2

array([1, 4, 9])

In [246]:
# Take the Sin Cos Tan
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

## Linear ALgebra

In [254]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print (b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [256]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [258]:
## Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [262]:
## Statistics

In [270]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [278]:
np.min(stats)

1

In [280]:
np.max(stats)

6

In [286]:
np.max(stats, axis =1)

array([3, 6])

In [288]:
## Reorganising Array

In [292]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print (before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [294]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print (before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [296]:
#Vertically Stacking Vectors

In [298]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.stack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
np.stack([v1,v2])

NameError: name 'np' is not defined

In [302]:
np.stack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [304]:
#Horizontal Stacking

In [306]:
h1 = np.zeros((2,4))
h2 = np.ones((2,2))

print(h1)
print(h2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [308]:
np.hstack((h1,h2))

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [ ]:
# Miscellaneous
Load Data from File


In [ ]:
#it will show as erroe as I have no data pasted in .txt file

In [2]:
filedata = np.genfromtxt( 'data.txt', delimiter = ",")

NameError: name 'np' is not defined

In [4]:
filedata.astype ("int32")
filedata

NameError: name 'filedata' is not defined

In [6]:
## Boolean Masking and Advanced Indexing

In [8]:
filedata > 50

NameError: name 'filedata' is not defined

In [10]:
filedata[filedata > 50]

NameError: name 'filedata' is not defined

In [20]:
## You can get index with a list in NumPy

In [2]:
w = np.array([1,2,3,4,5,6,7,8,9])

NameError: name 'np' is not defined